### ISSUE TITLE
Redmine 2.3.2 versus Eclipse Indigo 3.7 or Eclipse Juno

### ISSUE THREAD

**Issue by belmontl** [ljader/redmine-mylyn-plugin#27]
Hi,
I've installed on server Redmine 2.3.2 with plugin redmine_mylyn_connector 2.8.2.stable.

I triy to link Eclipse with Redmine but it does not work, neither with Eclipse Indigo or Eclipse Juno.
I've installed the plugin 0.4 with instruction on page https://github.com/ljader/redmine-mylyn-plugin.

Is there anything else to do?

Do the plugin "plugin redmine_mylyn_connector" and "plugin redmine_mylyn_plugin" are the same?

Thank for help

**Comment by ogarzonm** [comment]
Excelent with the API key works

**Comment by awilkins** [comment]
> the plugin "plugin redmine_mylyn_connector" and "plugin redmine_mylyn_plugin" are the same

There are two parts you need for it all to work 

1. A Redmine plugin for the server
1. A Mylyn connector for the client

The Mylyn project in particular has always called the component that adds support for another server a "connector", and Redmine usually calls additional components "plugin" - alas, the original software project got this the wrong way around and called the server-side component a connector and the client side component a plugin. Confusion persists unto this day.

The other thing that causes confusion is that the two pieces of software are maintained by different groups of people in different repositories, not even grouped as one project.

TBH, the whole project needs reorganizing, there needs to be a more structured approach to following the API changes to the main Redmine project, etc. But the people working on it are a loose collective of people scratching their own itches, so this is a bit much to ask.

**Comment by ljader** [comment]
@alfonsomunozpomer and @ogarzonm 
Enabled REST web service is **required** for Redmine-Mylyn integration to work.
Having that enabled, the both methods: API key an user/password will work.

I've updated installation description in [README.md](https://github.com/ljader/redmine-mylyn-plugin/blob/master/README.md) so I'm closing this issue.
