### ISSUE TITLE
404 and 405 trying to add tasks

### ISSUE THREAD

**Issue by sdfg2** [ljader/redmine-mylyn-plugin#29]
Whenever I try and create a task I get an error 404, and whenever I try and edit an already existing task that I've created through the website, I get error 405.  I can't see anything server side, and I'm not sure where to look client side to get more information.

Can anyone help?  This is the last piece of my redmine+eclipse puzzle, I'd love to get it fixed.

steve

**Comment by ljader** [comment]
As per @sdfg2  last comment, this has been fixed with Redmine setup with additional /redmine path instead of raw redmine.domain.com subdomain.
Thank you all for your help.
