### ISSUE TITLE
User/Password login doesn’t work (only REST API key)

### ISSUE THREAD

**Issue by alfonsomunozpomer** [ljader/redmine-mylyn-plugin#32]
I open this issue for any user who may have found this problem adding their Redmine repository.

[Instructions for enabling REST access](https://github.com/ljader/redmine-mylyn-plugin/issues/27#issuecomment-28194715).

**Comment by ljader** [comment]
@alfonsomunozpomer
Enabled REST web service is **required** for Redmine-Mylyn integration to work.
Having that enabled, the both methods: API key an user/password will work.

I've updated installation description in [README.md](https://github.com/ljader/redmine-mylyn-plugin/blob/master/README.md) so I'm closing this issue.
