### ISSUE TITLE
eclipse kepler and redmine 2.3.1

### ISSUE THREAD

**Issue by ghost** [ljader/redmine-mylyn-plugin#35]
I have two installation of redmine. 
An old 1.3.2 and a new 2.3.1.
Problems are only with 2.3.1. 
With al newer versione of mylyn connector in redmine (2.8.2).
In eclipse kepler redmine plugin was the 0.4.0  (but I also test with older 0.3.7).
Trying to add the server with redmine 2.3.1 I alway have error 404.
No way to have more.
Is there some issue?

**Comment by ljader** [comment]
I'm closing this issue, because user can't be reached for more details.
