### ISSUE TITLE
Install fails in Eclipse, missing dependency?

### ISSUE THREAD

**Issue by catmanjan** [ljader/redmine-mylyn-plugin#40]
Fresh copy of Eclipse (install via inbuilt software manager) on a fresh copy of Fedora 20.

Using the ZIP link from the README.

Cannot complete the install because one or more required items could not be found.
  Software being installed: Mylyn Connector: Redmine 0.4.0.201402161233 (net.sf.redmine_mylyn.feature.feature.group 0.4.0.201402161233)
  Missing requirement: Logback Native SLF4J Logger Module 0.9.27.v20110224-1110 (ch.qos.logback.slf4j 0.9.27.v20110224-1110) requires 'bundle org.slf4j.api [1.6.1,1.7.0)' but it could not be found
  Cannot satisfy dependency:
    From: Mylyn Connector: Redmine 0.4.0.201402161233 (net.sf.redmine_mylyn.feature.feature.group 0.4.0.201402161233)
    To: ch.qos.logback.slf4j [0.9.27.v20110224-1110]

**Comment by dannychase2004** [comment]
The above worked for me, but it took me several hours of searching with trial and error, and tried several different packages.. Is it really this complicated or am I approaching these issues incorrectly? Why wouldn't the sourceforge project page just point to this link explicitly? See past my rant, anyone know an answer to my question?

**Comment by ljader** [comment]
This issue probably occurs, because dependencies are somehow fixed on old versions, and in Luna and Mars repositories those old artifacts are now gone.

I need to find some time to fix those dependencies, so the install would work out of the box - sorry for the delays.

**Comment by dannychase2004** [comment]
Thanks for the response!

**Comment by ljader** [comment]
I'm closing this issue, because:
* [README.md](https://github.com/ljader/redmine-mylyn-plugin/blob/master/README.md) has been updated with installation instructions.
* [GitHub Releases](https://github.com/ljader/redmine-mylyn-plugin/releases/latest) contains ZIP with P2 repo for latest version (currently 0.4.0) of the plugin.

Please check that out!
