### ISSUE TITLE
Missing Tasks

### ISSUE THREAD

**Issue by digitalwizard79** [ljader/redmine-mylyn-plugin#41]
After creating a query, I noticed that there are several tasks missing. I have uninstalled and re-installed and tried on different versions of eclipse, but the same results. I get approximately 33 tasks pulled down when there are several more that should be showing up.

**Comment by ljader** [comment]
Hi @digitalwizard79 , were the missing tasks assigned to different user which user/pass was configured in "Task Repositories" view?

**Comment by ljader** [comment]
I'm closing this issue, since there were no update from the author.
