### ISSUE TITLE
Cannot install on Mars

### ISSUE THREAD

**Issue by zulus** [ljader/redmine-mylyn-plugin#58]
Error:
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Mylyn Connector: Redmine 0.4.0.201502061644 (net.sf.redmine_mylyn.feature.feature.group 0.4.0.201502061644)
  Missing requirement: Logback Native SLF4J Logger Module 0.9.27.v20110224-1110 (ch.qos.logback.slf4j 0.9.27.v20110224-1110) requires 'bundle org.slf4j.api [1.6.1,1.7.0)' but it could not be found
  Cannot satisfy dependency:
    From: Mylyn Connector: Redmine 0.4.0.201502061644 (net.sf.redmine_mylyn.feature.feature.group 0.4.0.201502061644)
    To: ch.qos.logback.slf4j [0.9.27.v20110224-1110]
```

**Comment by awilkins** [comment]
Have pushed a new revision with a mars profile

Check out latest master, do

    mvn clean package -Pplatform-mars

Artifacts are built to

    ./net.sf.redmine_mylyn.p2repository/target/

Install from local zip file.

Note that I've not tested this at all, I don't have the time, I look forward to your feedback.

**Comment by zulus** [comment]
No luck. Same error.

Workaround is add old plugin (because its composite repo with orbit) or orbit p2 to eclipse configuration.
After that I'm able to install on mars.

**Comment by hedayat** [comment]
This issue is not related to Eclipse Mars. I have had the same problem with older versions of Eclipse and the fix was to add http://redmin-mylyncon.sourceforge.net/update-site/N repository.

**Comment by zulus** [comment]
Commit bc3ae8893958d3228dda8b3d0268b91891375f4a resolves issue.
