### ISSUE TITLE
Extemly slow comment typing. 

### ISSUE THREAD

**Issue by zulus** [ljader/redmine-mylyn-plugin#63]
Lag on each letter.

Tested on Mars.

**Comment by ljader** [comment]
@zulus I've tested it with Mars 4.5.1 64bit and JDK 7 on Windows 7 and I didnt see any lag.

What was your environment where the bug occurs?

**Comment by zulus** [comment]
On 4.5.1 works much better. Probably related to Mylyn Wikitext directly.

BTW: As far as I know they plan to replace parser in neon.
