### ISSUE TITLE
P2P repo download link is broken

### ISSUE THREAD

**Issue by anton-potapov** [ljader/redmine-mylyn-plugin#64]
link to "local" zip repo showing error 404.

**Comment by ljader** [comment]
One of pull requests bumped version to 0.4.1-SNAPSHOT - I need to revise it and decide if merge.

As a workaround you can use this link:
https://buildhive.cloudbees.com/job/ljader/job/redmine-mylyn-plugin/lastSuccessfulBuild/net.sf.redmine_mylyn$net.sf.redmine_mylyn.p2repository/artifact/net.sf.redmine_mylyn/net.sf.redmine_mylyn.p2repository/0.4.1-SNAPSHOT/net.sf.redmine_mylyn.p2repository-0.4.1-SNAPSHOT.zip

**Comment by misterspook** [comment]
This is not active anymore.

**Comment by ljader** [comment]
[GitHub Releases](https://github.com/ljader/redmine-mylyn-plugin/releases/latest) has been updated with ZIP with P2 repo for latest version (currently 0.4.0) of the plugin.
