### ISSUE TITLE
can not install plugin

### ISSUE THREAD

**Issue by mato777** [ljader/redmine-mylyn-plugin#65]
The snapshot is broken and i don´t know how to compile the plugin and install it in Eclipse.
someone can help?

**Comment by ljader** [comment]
Your comment should contain more specific details about the issue - it took me a while to guess, that the link for ZIP from BuildHive is not working.

I'll look into Travis CI to build this plugin.

**Comment by mato777** [comment]
Thanks, I have donwloaded from repository the plugin but i don´t it is working. I get always a Unexpected 404 not found.  I have configure the plugin in the redmine server and i see it in the extensions menu and i also enable the rest api but still getting the 404.

Any thoughts?

**Comment by ljader** [comment]
@mato777 again, could you give more detais about your system?
- Redmine version
- Redmine Mylyn Eclipse Plugin version
- Redmine Mylyn Connector version and url where you get it
- are you connecting using API Key or User/Pass
- at what stage in Eclipse you see 404 - during connection or during creating query?

**Comment by mato777** [comment]
I see the connector plugin installed in the redmine web.  I get the 404 when I am building a query. 
I´ve got a snapshot with 4.0 but also get the same problem.  
I am using redmine 3.1.1 with Eclipse Mars 4.5.1 and the connector i´ve downloaded from 
http://redmin-mylyncon.sourceforge.net/update-site/N/
This my info:
  Mylyn Connector: Redmine	0.3.7.201203072118	net.sf.redmine_mylyn.feature.feature.group	Sven Krzyzak
  Mylyn Connector: Redmine - Redmine-Plugin-Support	0.1.0.201203072118	net.sf.redmine_mylyn.extensions.feature.feature.group	Sven Krzyzak

**Comment by worldwidemv** [comment]
Correct me if I am wrong but aren't you using the old Redmin-Mylyn connector for Eclipse???
Your download URL http://redmin-mylyncon.sourceforge.net/update-site/N/ suggests this.

If so, this is the wrong place to ask for advice!!!
You should check out http://redmin-mylyncon.sourceforge.net/ for help

**Comment by mato777** [comment]
i wrote that i've got the two versions and both failed to run the query,
they give a 404 unexpected result

**Comment by misterspook** [comment]
I have the same problem. The plugin is old that is the fact, where is the new version? I get an error in eclipse when testing the connection. That plugin (http://redmin-mylyncon.sourceforge.net/update-site/N/ ) is for redmine 1.0.0. 

We are installing the wrong version because we dont know how to install the version from this site.

Thanks

**Comment by misterspook** [comment]
You can install the mylyn incubator from official site. And then connect it via web connector. I did that and tis ok.

**Comment by mato777** [comment]
after a lot of work i got it.  it was some depency libraries in the redmine.  What is not working, is the part of a assigning a person to a task and the schedule for that task

**Comment by misterspook** [comment]
how did u install it? from this site or?
@mato777

**Comment by iki-cz** [comment]
Please provide a correct install instructions. Thx

**Comment by ljader** [comment]
@iki-cz @misterspook  I hope that I'll make the instruction at the end of this week.

**Comment by iki-cz** [comment]
Hello, I know, that "winter is comming", but do you have any update? :)

**Comment by misterspook** [comment]
Yes, do you have an update? This winter will be long. :)

**Comment by rfigura** [comment]
Since ljader is spending his free time for this project, I don't want to come across as pushy.
However, I just want to say that your project is very well received and I guess we are all looking forward to an update, as soon as it is ready. :-)
Thank you for all the good work!

**Comment by awilkins** [comment]
Basic (from source) installation instructions :

* Have Maven installed (if you're using Eclipse, likely you're a Java dev and already have this)
* Git clone the sources
* In the top level source folder, do `mvn clean package -Pplatform-mars`   # where platform-<name> should be the release name of your Eclipse
* This should take about 1-2 minutes to build with warm caches ; a little longer if you've never built any of it before (as Maven  and Tycho will fetch a load of components from remote servers.
    * Note in particular that Tycho isn't good at fetching components through a proxy, even if you have one configured for Maven
* You should end up with an update-site archive in `net.sf.redmine_mylyn.p2repository/target/`
* Use this archive to install the software from the "Install New Software" dialog
    * Push the button marked "Add", chose the archive, walk through the wizard.

Tested this on a fairly fresh install of Mars/PHP Dev Tools while I was typing this ; works fine.

Other pointers

* When defining a repository, expand the Task Editor settings and choose Textile (or Markdown if you reconfigured your Redmine instance to use the Markdown support).

**Comment by misterspook** [comment]
I do not end up with an archive when I run maven clean on top level source folder, 
I have some errors in the log file when building net.sf.redmine_mylyn.p2repository:

*[ERROR]   Software being installed: net.sf.redmine_mylyn.p2repository raw:0.4.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):0.4.0-SNAPSHOT
[ERROR]   Missing requirement: net.sf.redmine_mylyn.p2repository raw:0.4.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):0.4.0-SNAPSHOT requires 'net.sf.redmine_mylyn.feature.feature.group [0.4.0,0.4.1)' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: net.sf.redmine_mylyn:net.sf.redmine_mylyn.p2repository:0.4.0-SNAPSHOT @ C:\Users\dule\git\redmine-mylyn-plugin\net.sf.redmine_mylyn.p2repository\pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.*

**Comment by iki-cz** [comment]
thx to @awilkins
http://formit.cz/net.sf.redmine_mylyn.p2repository-0.4.0-SNAPSHOT.zip

**Comment by misterspook** [comment]
Great! Thanks

**Comment by ljader** [comment]
[README.md](https://github.com/ljader/redmine-mylyn-plugin/blob/master/README.md) has been updated with installation instructions.

[GitHub Releases](https://github.com/ljader/redmine-mylyn-plugin/releases/latest) contains ZIP with P2 repo for latest version (currently 0.4.0) of the plugin.

Please check that out!
