### ISSUE TITLE
Cannot complete the install 

### ISSUE THREAD

**Issue by devbau** [ljader/redmine-mylyn-plugin#69]
Got a link to the package:

iki-cz commented on Dec 10, 2015
thx to @awilkins
http://formit.cz/net.sf.redmine_mylyn.p2repository-0.4.0-SNAPSHOT.zip

but if I'm trying to install there is an error:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Mylyn Connector: Redmine 0.4.0.201512100615 (net.sf.redmine_mylyn.feature.feature.group 0.4.0.201512100615)
  Missing requirement: Mylyn Connector: Redmine 0.4.0.201512100615 (net.sf.redmine_mylyn.feature.feature.group 0.4.0.201512100615) requires 'org.eclipse.equinox.log 1.2.0' but it could not be found

**Comment by ljader** [comment]
Could you give more detais about your system?

    Redmine version
    Eclipse version
    Redmine Mylyn Eclipse Plugin version
    Redmine Mylyn Connector version and url where you get it
    are you connecting using API Key or User/Pass

**Comment by devbau** [comment]
Yes, sure.

http://postimg.org/image/jtn2wc4nr/

**Comment by devbau** [comment]
I'm unable to install plugin redmine-mylyn-plugin

**Comment by ljader** [comment]
@devbau do you have JEE or SDK or PHP or other version of Eclipse Luna SR2 (4.4.2) ?

Could you also try to install plugin from https://github.com/ljader/redmine-mylyn-plugin/releases/latest ?

**Comment by xsanz** [comment]
Hello, 
I can't install it also,
I'm using a Eclipse Mars 4.5.2 PDT
Thank you

**Comment by ljader** [comment]
Hi all.
This should work in new 0.5.1 version of the plugin - https://github.com/ljader/redmine-mylyn-plugin/releases

Thank you all for your help.
