### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by tbuss** [ljader/redmine-mylyn-plugin#71]
I use Atollic 5.4.2 (which is used on Eclipse) and tried to ionstall the latest version of the plugin (net.sf.redmine_mylyn.p2repository-0.4.0.201602071631.zip) but it failed:

`Cannot complete the install because one or more required items could not be found.
  Software being installed: Mylyn Connector: Redmine 0.4.0.201602071631 (net.sf.redmine_mylyn.feature.feature.group 0.4.0.201602071631)
  Missing requirement: Mylyn Connector: Redmine 0.4.0.201602071631 (net.sf.redmine_mylyn.feature.feature.group 0.4.0.201602071631) requires 'org.eclipse.equinox.log 1.2.0' but it could not be found`

I can see that there is installed:
`Eclipse Platform   4.3.0.v20130605-2000    org.eclipse.platform.feature.group  Eclipse.org`
and also
`Equinox p2 Core Function   1.2.0.v20130604-2046    org.eclipse.equinox.p2.core.feature.feature.group   Eclipse.org - Equinox`

Any idea or suggestions what I can try/do?

**Comment by awilkins** [comment]
My usual advice for dependency problems : build the plugin from source and install from the local archive it builds.

Eclipse 4.3 is Kepler so you want to ....

    mvn clean package -Pplatform-kepler

**Comment by ljader** [comment]
Hi all.
This has been fixed in new 0.5.1 version of the plugin - https://github.com/ljader/redmine-mylyn-plugin/releases

Thank you all for your help.
