### ISSUE TITLE
Link to redmine 3.x compatible redmine plugin

### ISSUE THREAD

**Issue by hedayat** [ljader/redmine-mylyn-plugin#72]
This should work on redmine 3 & later (I've installed it and it works for me):
https://github.com/joaopedrotaveira/redmine_mylyn_connector

**Comment by ljader** [comment]
Hi all.
The README.md has been updated in new 0.5.1 version of the plugin - https://github.com/ljader/redmine-mylyn-plugin/releases

Thank you all for your help.
